# Generated by Django 3.2.19 on 2023-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../img/baking-mama-footer.f58025d9dfa6.png', upload_to='images/'),
        ),
    ]
